"""中国体彩网队名映射表（英文→中文）
用于将CSV英文队名转换为体彩网中文名进行匹配。
"""

# 完整映射：英文队名/别名 → 体彩中文网名
SPORTTERY_TEAM_MAP = {
    # 英超
    "arsenal": "阿森纳",
    "arsenal fc": "阿森纳",
    "aston villa": "阿斯顿维拉",
    "aston villa fc": "阿斯顿维拉",
    "brighton": "布莱顿",
    "brighton & hove albion": "布莱顿",
    "brighton and hove albion": "布莱顿",
    "brighton and hove albion fc": "布莱顿",
    "chelsea": "切尔西",
    "chelsea fc": "切尔西",
    "crystal palace": "水晶宫",
    "crystal palace fc": "水晶宫",
    "everton": "埃弗顿",
    "everton fc": "埃弗顿",
    "fulham": "富勒姆",
    "fulham fc": "富勒姆",
    "liverpool": "利物浦",
    "liverpool fc": "利物浦",
    "manchester city": "曼城",
    "manchester city fc": "曼城",
    "mcfc": "曼城",
    "manchester united": "曼联",
    "manchester united fc": "曼联",
    "man utd": "曼联",
    "man utd": "曼联",
    "manu": "曼联",
    "newcastle": "纽卡斯尔",
    "newcastle united": "纽卡斯尔",
    "newcastle united fc": "纽卡斯尔",
    "nottingham forest": "诺丁汉森林",
    "nottingham forest fc": "诺丁汉森林",
    "tottenham": "热刺",
    "tottenham hotspur": "热刺",
    "tottenham hotspur fc": "热刺",
    "west ham": "西汉姆联",
    "west ham united": "西汉姆联",
    "west ham united fc": "西汉姆联",
    "brentford": "布伦特福德",
    "brentford fc": "布伦特福德",
    "wolves": "狼队",
    "wolverhampton": "狼队",
    "wolverhampton wanderers": "狼队",
    "bournemouth": "伯恩茅斯",
    "afc bournemouth": "伯恩茅斯",
    "leicester": "莱斯特城",
    "leicester city": "莱斯特城",
    "leicester city fc": "莱斯特城",
    "ipswich": "伊普斯维奇",
    "ipswich town": "伊普斯维奇",
    "ipswich town fc": "伊普斯维奇",
    "southampton": "南安普顿",
    "southampton fc": "南安普顿",
    "stoke": "斯托克城",
    "stoke city": "斯托克城",
    "stoke city fc": "斯托克城",
    "burnley": "布伦利",
    "burnley afc": "布伦利",
    "leeds": "利兹联",
    "leeds united": "利兹联",
    "leeds united fc": "利兹联",
    "norwich": "诺维奇",
    "norwich city": "诺维奇",
    "norwich city fc": "诺维奇",

    # 西甲
    "real madrid": "皇马",
    "real madrid cf": "皇马",
    "barcelona": "巴萨",
    "fc barcelona": "巴萨",
    "atletico madrid": "马竞",
    "club atletico de madrid": "马竞",
    "athletic club": "毕尔巴鄂竞技",
    "athletic bilbao": "毕尔巴鄂竞技",
    "real sociedad": "皇家社会",
    "real sociedad de futbol": "皇家社会",
    "real betis": "贝蒂斯",
    "real betis balompie": "贝蒂斯",
    "villarreal": "比利亚雷亚尔",
    "villarreal cf": "比利亚雷亚尔",
    "girona": "赫罗纳",
    "girona fc": "赫罗纳",
    "osasuna": "奥萨苏纳",
    "ca osasuna": "奥萨苏纳",
    "mallorca": "马略卡",
    "rcd mallorca": "马略卡",
    "getafe": "赫塔费",
    "getafe cf": "赫塔费",
    "alaves": "阿拉维斯",
    "deportivo alaves": "阿拉维斯",
    "celta": "塞尔塔",
    "celta de vigo": "塞尔塔",
    "rayo vallecano": "巴列卡诺",
    "espanyol": "西班牙人",
    "rcd espanyol": "西班牙人",
    "espanyol de barcelona": "西班牙人",
    "leganes": "莱加内斯",
    "cd leganes": "莱加内斯",
    "valladolid": "巴拉多利德",
    "real valladolid": "巴拉多利德",
    "las palmas": "拉斯帕尔马斯",
    "ud las palmas": "拉斯帕尔马斯",
    "sevilla": "塞维利亚",
    "sevilla fc": "塞维利亚",
    "valencia": "瓦伦西亚",
    "valencia cf": "瓦伦西亚",
    "elche": "埃尔切",
    "elche cf": "埃尔切",
    "granada": "格拉纳达",
    "granada cf": "格拉纳达",
    "cadiz": "加的斯",
    "cadiz cf": "加的斯",
    "almeria": "阿尔梅里亚",
    "ud almeria": "阿尔梅里亚",
    "levante": "莱万特",
    "levante ud": "莱万特",

    # 德甲
    "bayern munich": "拜仁慕尼黑",
    "bayern muenchen": "拜仁慕尼黑",
    "fc bayern munich": "拜仁慕尼黑",
    "bayern munich e.V.": "拜仁慕尼黑",
    "borussia dortmund": "多特蒙德",
    "bvb 09": "多特蒙德",
    "bayer leverkusen": "勒沃库森",
    "bayer 04 leverkusen": "勒沃库森",
    "rb leipzig": "莱比锡红牛",
    "rasenballsport leipzig": "莱比锡红牛",
    "frankfurt": "法兰克福",
    "eintracht frankfurt": "法兰克福",
    "stuttgart": "斯图加特",
    "vfb stuttgart": "斯图加特",
    "freiburg": "弗赖堡",
    "sc freiburg": "弗赖堡",
    "bremen": "云达不莱梅",
    "werder bremen": "云达不莱梅",
    " Gladbach": "门兴格拉德巴赫",
    "gladbach": "门兴格拉德巴赫",
    "borussia monchengladbach": "门兴格拉德巴赫",
    "mainz": "美因茨",
    "mainz 05": "美因茨",
    "1. fsv mainz 05": "美因茨",
    "hoffenheim": "霍芬海姆",
    "tsg hoffenheim": "霍芬海姆",
    "augsburg": "奥格斯堡",
    "fc augsburg": "奥格斯堡",
    "union berlin": "柏林联合",
    "1. fc union berlin": "柏林联合",
    "koln": "科隆",
    "1. fc koln": "科隆",
    "wolfsburg": "沃尔夫斯堡",
    "vfl wolfsburg": "沃尔夫斯堡",
    "darmstadt": "达姆施塔特",
    "sv darmstadt 98": "达姆施塔特",
    "heidenheim": "海登海姆",
    "heidenheim 1846": "海登海姆",
    "bochum": "波鸿",
    "vfl bochum": "波鸿",
    "vfl bochum 1848": "波鸿",

    # 意甲
    "milan": "AC米兰",
    "ac milan": "AC米兰",
    "inter milano": "国际米兰",
    "inter milan": "国际米兰",
    "fc inter milano": "国际米兰",
    "juventus": "尤文图斯",
    "juventus fc": "尤文图斯",
    "napoli": "那不勒斯",
    "ssc napoli": "那不勒斯",
    "roma": "罗马",
    "as roma": "罗马",
    "lazio": "拉齐奥",
    "ss lazio": "拉齐奥",
    "atalanta": "亚特兰大",
    "atalanta bc": "亚特兰大",
    "fiorentina": "佛罗伦萨",
    "acf fiorentina": "佛罗伦萨",
    "bologna": "博洛尼亚",
    "bologna fc": "博洛尼亚",
    "torino": "都灵",
    "torino fc": "都灵",
    "udinese": "乌迪内斯",
    "udinese calcio": "乌迪内斯",
    "genoa": "热那亚",
    "genoa cfc": "热那亚",
    "sassuolo": "萨索洛",
    "us sassuolo calcio": "萨索洛",
    "cagliari": "卡利亚里",
    "cagliari calcio": "卡利亚里",
    "lecce": "莱切",
    "us lecce": "莱切",
    "empoli": "恩波利",
    "empoli fc": "恩波利",
    "verona": "维罗纳",
    "hellas verona": "维罗纳",
    "frosinone": "弗洛西诺",
    "frosinone calcio": "弗洛西诺",
    "monza": "蒙扎",
    "ac monza": "蒙扎",
    "salernitana": "萨勒尼塔纳",
    "us salernitana": "萨勒尼塔纳",
    "sampdoria": "桑普多利亚",
    "uc sampdoria": "桑普多利亚",
    "parma": "帕尔马",
    "parma calcio": "帕尔马",
    "como": "科莫",
    "como 1907": "科莫",
    "venezia": "威尼斯",
    "venezia fc": "威尼斯",

    # 法甲
    "psg": "巴黎圣日耳曼",
    "paris saint-germain": "巴黎圣日耳曼",
    "paris saint-germain fc": "巴黎圣日耳曼",
    "marseille": "马赛",
    "olympique de marseille": "马赛",
    "lyon": "里昂",
    "olympique lyonnais": "里昂",
    "monaco": "摩纳哥",
    "as monaco": "摩纳哥",
    "lille": "里尔",
    "losc lille": "里尔",
    "nice": "尼斯",
    "ogc nice": "尼斯",
    "rennes": "雷恩",
    "stade rennais": "雷恩",
    "strasbourg": "斯特拉斯堡",
    "rc strasbourg alsace": "斯特拉斯堡",
    "nantes": "南特",
    "fc nantes": "南特",
    "brest": "布雷斯特",
    "stade brestois": "布雷斯特",
    "lens": "朗斯",
    "rc lens": "朗斯",
    "reims": "兰斯",
    "stade de reims": "兰斯",
    "montpellier": "蒙彼利埃",
    "montpellier hsc": "蒙彼利埃",
    "toulouse": "图卢兹",
    "toulouse fc": "图卢兹",
    "angers": "昂热",
    "angers sco": "昂热",
    "auxerre": "欧塞尔",
    "aj auxerre": "欧塞尔",
    "le havre": "勒阿弗尔",
    "le havre ac": "勒阿弗尔",
    "clermont": "克莱蒙",
    "clermont foot": "克莱蒙",
    "metz": "梅斯",
    "fc metz": "梅斯",
    "lorient": "洛里昂",
    "fc lorient": "洛里昂",
    "meux": "梅斯",

    # 荷甲
    "ajax": "阿贾克斯",
    "afc ajax": "阿贾克斯",
    "az alkmaar": "阿尔克马尔",
    "az": "阿尔克马尔",
    "almere city": "阿尔梅勒城",
    "groningen": "格罗宁根",
    "fc groningen": "格罗宁根",
    "twente": "特温特",
    "fc twente": "特温特",
    "utrecht": "乌德勒支",
    "fc utrecht": "乌德勒支",
    "volendam": "福伦丹",
    "feyenoord": "费耶诺德",
    "feyenoord rotterdam": "费耶诺德",
    "fortuna sittard": "福图纳锡塔德",
    "go ahead eagles": "前进之鹰",
    "heracles": "赫拉克勒斯",
    "heracles almelo": "赫拉克勒斯",
    "nac breda": "布雷达",
    " NEC": "奈梅亨",
    "pec zwolle": "兹沃勒",
    "psv": "埃因霍温",
    "psv eindhoven": "埃因霍温",
    "rkc waalwijk": "瓦尔韦克",
    "excelsior": "精英",
    "vitesse": "维特斯",
    "heerenveen": "海伦芬",
    "sparta rott erdam": "鹿特丹斯巴达",
    "telstar": "泰勒斯塔",
    "willem ii": "威廉二世",

    # 葡超
    "benfica": "本菲卡",
    "sl benfica": "本菲卡",
    "porto": "波尔图",
    "fc porto": "波尔图",
    "sporting": "葡萄牙体育",
    "sporting cp": "葡萄牙体育",
    "braga": "布拉加",
    "sporting clube de braga": "布拉加",
    "avs": "阿维斯",
    "boavista": "博阿维斯塔",
    "nacional": "国民队",
    "santa clara": "圣克拉拉",
    "tondela": "通德拉",
    "estrela amadora": "阿马多拉之星",
    "casa pia": "卡萨皮亚",
    "alverca": "阿尔韦卡",
    "arouca": "阿罗卡",
    "famalicao": "法马利康",
    "vizela": "维泽拉",
    "chaves": "查维斯",
    "estoril": "埃斯托里尔",
    "gil vicente": "吉尔维森特",
    "moreirense": "摩雷伦斯",
    "portimonense": "波尔蒂芒人",
    "rio ave": "里奥阿维",
    "farense": "法伦斯",
    "guimaraes": "吉马良斯",
    "vitoria guimaraes": "吉马良斯",

    # 欧冠（欧战）
    "celtic": "凯尔特人",
    "celtic fc": "凯尔特人",

    # 巴甲
    "santos": "桑托斯",
    "santos fc": "桑托斯",
    "mirassol": "米拉索尔",
    "botafogo": "博塔弗戈",
    "botafogo fr": "博塔弗戈",
    "flamengo": "弗拉门戈",
    "flamengo rj": "弗拉门戈",
    "palmeiras": "帕尔梅拉斯",
    "palmeiras br": "帕尔梅拉斯",
    "atletico mineiro": "米内罗竞技",
    "atletico mg": "米内罗竞技",
    "corinthians": "科林蒂安",
    "sc corinthians paulista": "科林蒂安",
    " sao paulo": "圣保罗",
    "saopaulo fc": "圣保罗",
    "fluminense": "弗鲁米嫩塞",
    "fluminense fc": "弗鲁米嫩塞",
    "vasco da gama": "瓦斯科达伽马",
    "vasco": "瓦斯科达伽马",
    "gremio": "格雷米奥",
    "gremio fbpa": "格雷米奥",
    "inter porto alegre": "国际体育会",
    "sporting cruz": "克鲁塞罗",
    "cruzeiro ec": "克鲁塞罗",
    "bahia": "巴伊亚",
    "ec bahia": "巴伊亚",
    "fortaleza": "福塔莱萨",
    "fortaleza ec": "福塔莱萨",
    "coritiba": "科里蒂巴",
    "coxilha": "科xis",
    "guarani": "瓜拉尼",
    "ponte pret a": "庞特普雷塔",

    # 美职
    "new england revolution": "新英格兰革命",
    "new england": "新英格兰",
    "new york city fc": "纽约城",
    "new york city": "纽约城",
    "la galaxy": "洛杉矶银河",
    "la galaxy fc": "洛杉矶银河",
    "inter mill": "迈阿密国际",
    "inter Miami": "迈阿密国际",
    "seattle sounders": "西雅图音速",
    "portland timbers": "波特兰伐木工",
    "atlanta united": "亚特兰大联",
    "orlando city": "奥兰多城",
    "fc dallas": "达拉斯FC",
    "houston dynamo": "休斯顿迪纳摩",
    " Sporting KC": "堪萨斯城Sporting",
    "real salt lake": "皇家盐湖城",
    "vancouver whitecaps": "温哥华白帽",
    "toronto fc": "多伦多FC",
    "montreal impact": "蒙特利尔冲击",
    "chicago fire": "芝加哥火焰",
    "columbus crew": "哥伦布机员",
    "philladelphia union": "费城联合",
    " Washington d.c. united": "华盛顿联",
    "san jose earthquake": "圣何塞地震",
    "colorado rapids": "科罗拉多急流",
    "minnesota united": "明尼苏达联",
    "dfw fc": "达拉斯FC",
    "ne": "新英格兰",
    "nycfc": "纽约城",
    "lafcc": "洛杉矶FC",
    "intermi": "迈阿密国际",

    # 更多西甲（补全）
    "sporting gijon": "希洪竞技",
    "sporting gijon": "希洪",
    "racing santander": "桑坦德竞技",
    "racing santander": "桑坦德",  # 别名
    "real oviedo": "奥维耶多",
    "real saragossa": "萨拉戈萨",
    "deportivo la coruna": "拉科鲁尼亚",
    "deportivo la coro": "拉科鲁尼亚",
    "deportivo la coruna": "拉科",  # 别名
    "real saragozo": "萨拉戈萨",
    "racing de sandober": "桑坦德",
    "racib gijon": "希洪",
    "racing santaber": "桑坦德",

    # 瑞超
    "malmo ff": "马尔默",
    "malmo": "马尔默",
    "djurgarden": "佐加顿斯",
    "djurgardens ifs": "佐加顿斯",

    # 葡超补充
    "vitoria guimaraes": "吉维森特",
    "sc braga": "布拉加",
}

# 反向映射（中文→英文）- 用于将CSV英文转为体彩中文
def get_chinese_name(english_name):
    """将英文队名转换为体彩中文网名"""
    if not english_name:
        return english_name
    key = english_name.lower().strip()
    return SPORTTERY_TEAM_MAP.get(key, english_name)

def get_english_name(chinese_name):
    """将体彩中文网名转换为英文（用于查找）"""
    if not chinese_name:
        return chinese_name
    # 反向查找
    for eng, cn in SPORTTERY_TEAM_MAP.items():
        if cn == chinese_name:
            return eng
    return chinese_name
